- src: robertdebock.bootstrap

- src: git+https://github.com/AutomationWithAnsible/ansible-apt
  version: "v0.4.1"
  name: ansible-apt

- src: git+https://github.com/yetu/ansible-hostname.git
  version: "v0.1.2"
  name: ansible-hostname

- src: git+https://github.com/Stouts/Stouts.sudo.git
  version: "1.0.0"

- src: git+https://github.com/ANXS/openssh.git
  version: "v1.0.1"
  name: ANXS.openssh

- src: git+https://github.com/knopki/ansible-locale.git
  version: "v1.0.3"
  name: knopki.locale

- src: galaxyproject.postgresql

- src: geerlingguy.java

- src: git+https://github.com/AutomationWithAnsible/ansible-nginx.git
  version: "v1.0.3"
  name: ansible-nginx

- src: alphanodes.postgresql-client

- src: manala.motd

- src: geerlingguy.apache

- src: bas-ansible-roles-collection.postgresql9-client

- src: marcelnijenhof.firewalld

- src: geerlingguy.nfs

- src: ajsalminen.hosts

- src: robertdebock.squid
