---
# SELinux permissive mode, logging actions that would be blocked
# e.g. required on proxy to allow http connection to nexus
# this could also be done with command below on proxy 
# /usr/sbin/setsebool -P httpd_can_network_connect 1
- name: Put SELinux in permissive mode
  selinux:
    policy: targeted
    state: permissive
  when: common_selinux_permissive == True    

- name: NFS mounts
  mount:
    path: "{{ item['path'] }}"
    src: "{{ item['src'] }}"
    fstype: "{{ item['fstype'] }}"
    opts: "{{ item['opts'] }}"
    state: "{{ item['state'] }}"
  with_items: '{{ nfs_mounts }}'
  ignore_errors: True

- name: etc environment
  template:
   src: etc_environment.j2
   dest: /etc/environment

- name: Role packages
  package:
    name: '{{ common_role_packages[item] }}'
    state: present
  when: common_role_packages[item] is defined
  with_items: '{{ common_role_packages }}'

- name: Add Ansible user
  user:
    name: '{{ common_ansible_user }}'
    comment: Ansible 
    shell: /bin/bash
    password: '{{ common_ansible_user_password }}'
    expires: '{{ common_ansible_user_expires }}'
  when: common_ansible_user_create == true

- name: Set authorized keys taken from url
  authorized_key:
    user: '{{ common_ansible_user }}'
    state: present
    key: '{{ common_ansible_authorized_keys }}'
    validate_certs: '{{ common_authorized_key_validate_certs }}'
  when: common_ansible_authorized_keys is defined    

- name: Custom prompt
  copy:
    content: 'export PS1="{{ common_terminal_prompt }}"'
    dest: /etc/profile.d/tpelcm_promp.sh 
  when: common_terminal_prompt is defined

- name: Remove custom prompt
  file:
    state: absent
    path: /etc/profile.d/tpelcm_promp.sh
  when: common_terminal_prompt is not defined
