---
proxy_allowed_ips: 
  - 1.1.1.2
  - 1.1.1.3
  - 1.1.1.4
  - 1.1.1.7
  - 1.1.1.8

squid_acls:
  - name: localnet
    classifier: src
    value: "\"{{ proxy_allowd_ips_file }}\""

# dynamic vars set in a role cannot be used on other roles 
# so we set squid_config_directory, squid_config_file here
squid_config_directory: /etc/squid 
squid_config_file: squid.conf
squid_conf_include_dir: /etc/squid/conf.d

# Configure upstream proxy server
# proxy_upstream_server: 10.0.2.2
# proxy_upstream_port: 8888

reverse_proxy_vhosts:
  sh:
    server_name: sh.1.1.1.3.nip.io 
    port: 443
    proxy_verify: false
    proxy_passes:
      sq:
        proxy_pass: /sonarqube https://1.1.1.4/sonarqube
        #proxy_pass_reverse: /sonarqube https://1.1.1.4/sonarqube/
      nexus:
        proxy_pass: /nexus http://1.1.1.7:8081/nexus nocanon
        proxy_pass_reverse: /nexus http://1.1.1.7:8081/nexus
#squid_cache_rules:
#  - acl: localnet
#    decision: deny


