---
c2_alias_prefix: tpelcm
c2_alias_editor: nano

c2_alias_roles: ['proxy', 'opendj', 'nexus', 'bitbucket','postfix', 'nfs', 'reverse-proxy', 'postgresql']

c2_alias:
  roles:
    proxy:
      logs: ["/var/log/squid/*.log","/var/log/squid/squid.out"]
      configs: 
        - "{{ squid_config_directory | default(omit) }}/{{ squid_config_file | default(omit) }}"
        - "{{ proxy_allowd_ips_file | default(omit) }}"
        - "{{ proxy_upstream_always_direct_file | default(omit) }}"
    opendj:
      logs: 
        - /opt/opendj/logs/server.out
        - /opt/opendj/logs/errors
        - /opt/opendj/logs/access
      configs: 
        - /etc/systemd/system/opendj.service
    nexus:
      logs: ["{{ nexus_data_dir | default(omit) }}/log/*.log"]
      configs: 
        - /etc/systemd/system/nexus.service
        - "{{ nexus_home | default(omit) }}/nexus-latest/etc/jetty/jetty-https.xml"
        - "{{ nexus_home | default(omit) }}/nexus-latest/etc/nexus-default.properties"
        - "{{ nexus_home | default(omit) }}/nexus-latest/etc/nexus.properties"
    bitbucket:
      logs: ["/opt/bitbucket/bitbucket/home/log/*.log"]
      configs: 
        - /etc/systemd/system/bitbucket.service
        - /opt/bitbucket/bitbucket/home/shared/bitbucket.properties
    postfix:
      logs: ['/var/log/maillog']
      configs:
        - /etc/postfix/main.cf
    postgresql:
      logs: ["/var/lib/pgsql/9.6/data/pg_log/*.log"]
      configs: 
        - "/var/lib/pgsql/{{ postgresql_version | default(omit) }}/data/pg_hba.conf"
        - "/var/lib/pgsql/{{ postgresql_version | default(omit) }}/data/postgresql.conf"
    nfs:
      logs: []
      configs:
        - /etc/exports
    reverse-proxy:
      logs: []
      configs:
        - /etc/httpd/conf.d/reverse_proxy.conf





