---
common_packages: 
  Debian: ['nfs-common', 'nano' ] 
  RedHat: ['nfs-utils', 'nano' ]

#'libffi-dev','libpq-dev'
#'libffi-devel'
#,'python-psycopg2'

common_etc_environment: >
  PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin 

nfs_server: nfs
nfs_mounts:
  - { path: /backup, src: '{{ nfs_server }}:/nfs/backup', opts: rw, fstype: nfs, state: mounted }

common_ansible_user_create: true

sudo_enabled: yes
sudo_users: [tpetools]
# sudo_groups: [admin, sudo]
# sudo_passwordless: [admin, sudo]

# common_ansible_authorized_keys: https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant.pub
common_ansible_user_password: whuq0hKZYtmE2

# common_terminal_prompt: '\e[01;31m[\u@{{ inventory_hostname }} \h \w]\\$\e[m '

swid_enable: true