---
- name: Keystore directory
  file:
    path: "{{ confluence_keystore }}"
    state: directory

- name: Generate server private key
  openssl_privatekey:
    path: "{{ confluence_keystore }}/https.key"

- name: Create certificate signing request 
  openssl_csr:
    path: "{{ confluence_keystore }}/https.csr"
    privatekey_path: "{{ confluence_keystore }}/https.key"
    country_name: "NL"
    organization_name: ""
    email_address: ""
    common_name: "tomcat"

- name: Generate a Self Signed OpenSSL certificate.
  openssl_certificate:
    path: "{{ confluence_keystore }}/https.crt"
    privatekey_path: "{{ confluence_keystore }}/https.key"
    csr_path: "{{ confluence_keystore }}/https.csr"
    provider: selfsigned

- name: Generate PKCS#12 file
  openssl_pkcs12:
    action: export
    path: "{{ confluence_keystore }}/https.p12"
    friendly_name: tomcat
    privatekey_path: "{{ confluence_keystore }}/https.key"
    certificate_path: "{{ confluence_keystore }}/https.crt"
    state: present
    passphrase: changeit

- name: Import SSL certificate to JKS keystore
  java_cert:
    pkcs12_path: "{{ confluence_keystore }}/https.p12"
    pkcs12_alias: tomcat
    pkcs12_password: changeit
    cert_alias: tomcat
    keystore_path: "{{ confluence_keystore }}/keystore"
    keystore_type: "JKS"
    keystore_pass: changeit
    keystore_create: yes
    state: present
    executable: "{{ confluence_home_version_app }}/jre/bin/keytool"

- name: Chown keystore dir
  file:
    dest: "{{ confluence_keystore }}"
    owner: "{{ confluence_owner }}"
    group: "{{ confluence_group }}"
    recurse: yes
