---
- name: confluence-init.properties
  template:
    dest: "{{ confluence_home_version_app }}/confluence/WEB-INF/classes/confluence-init.properties"
    owner: "{{ confluence_owner }}"
    group: "{{ confluence_group }}"
    src: confluence-init.properties.j2
  notify: confluence-systemctl-restart

- name: server.xml
  template:
    dest: "{{ confluence_home_version_app }}/conf/server.xml"
    owner: "{{ confluence_owner }}"
    group: "{{ confluence_group }}"
    src: server.xml.j2
  notify: confluence-systemctl-restart

- name: web.xml
  template:
    dest: "{{ confluence_home_version_app }}/confluence/WEB-INF/web.xml"
    owner: "{{ confluence_owner }}"
    group: "{{ confluence_group }}"
    src: web.xml.j2
  notify: confluence-systemctl-restart


- name: Xms, Xmx and other CATALINA_OPTS in setenv.sh
  replace:
    path: "{{ confluence_home_version_app }}/bin/setenv.sh"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items: 
    - regexp: '^CATALINA_OPTS="-Xms.*$'
      replace: "CATALINA_OPTS=\"-Xms{{ confluence_jvm_minimum_memory }} -Xmx{{ confluence_jvm_maximum_memory }} -XX:+UseG1GC {{ confluence_cataline_opts }} ${CATALINA_OPTS}\""
    - regexp: '-XX:ReservedCodeCacheSize=.*? '
      replace: '-XX:ReservedCodeCacheSize={{ confluence_jvm_reserved_code_cache_size }} '
  notify: confluence-systemctl-restart

- name: Extra libaries
  get_url:
    checksum: "{{ item.checksum }}"
    dest: "{{ confluence_home_version_app }}/confluence/WEB-INF/lib/{{ item.url|basename }}"
    owner: "{{ confluence_owner }}"
    group: "{{ confluence_group }}"
    url: "{{ item.url }}"
  with_items: "{{ confluence_libraries }}" 
  notify: confluence-systemctl-restart

- name: Oracle JDBC driver
  get_url:
    dest: "{{ confluence_home_version_app }}/lib/{{ confluence_database_ojdbc_jar_url|basename }}"
    group: "{{ confluence_group }}"
    owner: "{{ confluence_owner }}"
    url: "{{ confluence_database_ojdbc_jar_url }}"
  when: confluence_database_ojdbc_jar_url is defined
  notify:
    - confluence-systemctl-restart
