---
bitbucket_home: /opt/bitbucket
bitbucket_scripts: /opt/bitbucket/scripts
bitbucket_mailto: "not-reply@example.com"

# bitbucket_version: 5.10.1
# bitbucket_version_prepare: 7.6.0
bitbucket_version: 7.6.0

bitbucket_jvm_minimum_memory: 512m
bitbucket_jvm_maximum_memory: 1g

bitbucket_web_port: 7990
bitbucket_web_context: '/bitbucket'

bitbucket_database_username: bitbucket
bitbucket_database_password: supersecure

bitbucket_database_host: localhost
bitbucket_database_port: "5432"
bitbucket_database_name: bitbucket
bitbucket_database_admin_username: ansible
bitbucket_database_admin_password: supersecure
bitbucket_database_template: template0
bitbucket_database_type: postgresql # oracle

# oracle example config
# bitbucket_database_name: BITBUCKET.localdomain
# bitbucket_database_type: oracle
# bitbucket_database_port: 1521

#bitbucket_database_jdbc_custom_config:
#  - jdbc.driver=org.postgresql.Driver
#  - jdbc...

bitbucket_owner: "bitbucket"
bitbucket_group: "bitbucket"

# Allow personal repos to be created
bitbucket_personal_repos: no

# TODO
#bitbucket_max_map_count: 262144

# Proxy and context path setup.
bitbucket_catalina_connector_proxyname: ~
bitbucket_catalina_connector_proxyport: ~
bitbucket_catalina_connector_scheme: "http"
bitbucket_catalina_connector_secure: "false"
bitbucket_catalina_context_path: "/"

# Atlassian Support recommended JVM arguments.
#bitbucket_jvm_support_recommended_args: >-
#  -Datlassian.plugins.enable.wait=300
#  -XX:+UnlockExperimentalVMOptions
#  -XX:+UseCGroupMemoryLimitForHeap
#  -XX:MaxRAMFraction=1

# Session timeout.
bitbucket_session_timeout: "300"

# Bitbucket inital setup
bitbucket_setup:
  display-name: Bitbucket
  base-url: https://sh.1.1.1.3.nip.io/bitbucket
  license: ''
  admin:
    username: admin
    password: supersecure
    display-name: Andy Kaufman
    mail: andy.kaufman@cicd.io

bitbucket_reverse_proxy:
  enable: yes
  secure: 'true'
  scheme: https
  port: 443
  hostname: sh.1.1.1.3.nip.io

#bitbucket_proxy:
#  host: localhost
#  port: 3128

# Facts set by lcm role - only
# bitbucket_database_name_version: bitbucket_6_7
# bitbucket_home_version: /opt/bitbucket/bitbucket_6_7

bitbucket_jmx:
  enable: yes
  remote_port: 3333
  rmi_port: 3333
  rmi_server_hostname: sh.1.1.1.11.nip.io
  password: supersecret

bitbucket_versions: 
  5.10.1:
    url: https://product-downloads.atlassian.com/software/stash/downloads/atlassian-bitbucket-5.10.1-linux-x64.bin
    checksum: sha256:d2807242530967ed4080a312128eccac2f46682ab986ceaba7fe91cf80840861
    installer_user: bitbucket
    # jdk:
  7.0.1:
    url: https://product-downloads.atlassian.com/software/stash/downloads/atlassian-bitbucket-7.0.1-x64.bin
    checksum: sha256:ad51613eee98671e0e81c41cded58af6dc69eb80bcaadbbb41e41684f3850717
  7.6.0:
    url: https://product-downloads.atlassian.com/software/stash/downloads/atlassian-bitbucket-7.6.0-x64.bin
    checksum: sha256:bcb6d73581f21ce6f8171bb415b3d798114df3589276442e3107c342397bf871
    installer_user: bitbucket
  7.8.0:
    url: https://product-downloads.atlassian.com/software/stash/downloads/atlassian-bitbucket-7.8.0-x64.bin
    checksum: sha256:8f9e90f1aa29238393f4c83379fb71cf838cf3696d2a112326f5b1c5bd7d34eb
    installer_user: bitbucket

bitbucket_packages:
  RedHat: ['fontconfig']
  CentOS: ['dejavu-sans-fonts','fontconfig']
  
bitbucket_versions_sequence: ['5.10.1','7.0.1','7.6.0', '7.8.0']
