---
- name: Set java folder
  set_fact:
    adoptopenjdk_java_folder: "{{ adoptopenjdk.version|lower }}"

- name: Set java_home
  set_fact:
    adoptopenjdk_java_home: "/usr/lib/jvm/{{ adoptopenjdk_java_folder }}"

- name: Check installed
  stat: 
    path: '{{ adoptopenjdk_java_home }}/bin/java'
  register: jdk_installed

- name: Download 
  get_url: 
    url: "{{ adoptopenjdk.versions[adoptopenjdk.version].url }}"
    dest: "/tmp/{{ adoptopenjdk_java_folder }}"
    checksum: "sha256:{{ adoptopenjdk.versions[adoptopenjdk.version].checksum }}" 

- name: Create java_home
  file:
    path: '{{ adoptopenjdk_java_home }}'
    state: directory

- name: Unarchive
  unarchive:
    src: '/tmp/{{ adoptopenjdk_java_folder }}'
    dest: '{{ adoptopenjdk_java_home }}'
    extra_opts: '--strip-components=1'
    remote_src: yes

- name: Java home in etc environment
  lineinfile: 
    dest: /etc/environment 
    regexp: '^JAVA_HOME'  
    line: 'JAVA_HOME={{ adoptopenjdk_java_home }}'
  when: adoptopenjdk_java_home_etc_environment == 'true'

- name: Profile jdk sh
  template:
    src: jdk.sh.j2
    dest: /etc/profile.d/jdk.sh
    mode: 0644
    
