---
jira_home: /opt/jira

jira_version: 7.12.1

jira_jvm_minimum_memory: 512m
jira_jvm_maximum_memory: 1g

jira_web_port: 8080
jira_web_context: /jira
jira_rmi_port: 8005

jira_owner: jira
jira_group: jira

jira_manual_upgrade: no

jira_database_username: jira
jira_database_password: supersecure

jira_database_host: localhost
jira_database_port: 5432
jira_database_name: jira
jira_database_admin_username: ansible
jira_database_admin_password: supersecure
jira_database_template: template0
jira_database_type_config: postgres72
jira_database_type: postgresql
jira_database_driver_class: org.postgresql.Driver
jira_database_validation_query: select 1
jira_database_schema: public
jira_datababse_setbigstringtryclob: no # yes for oracle
jira_database_lc_collate: C
jira_database_lc_ctype: C
# Oracle example settings
# jira_database_url: jdbc:oracle:thin:@//oracle:1521/JIRA.localdomain
# jira_database_url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=1.1.1.111)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=jira.localdomain)))
# jira_database_ojdbc_jar_url: https://example.com/ojdbc8.jar
# jira_database_driver_class: oracle.jdbc.OracleDriver
# jira_database_validation_query: select 1 from dual
# jira_database_type: oracle
# jira_database_type_config: oracle10g
# jira_database_schema: nil
# jira_datababse_setbigstringtryclob: yes

# Proxy and context path setup.
jira_proxy_name: sh.1.1.1.3.nip.io
jira_proxy_port: 443

jira_versions:
  7.12.1:
    url: https://product-downloads.atlassian.com/software/jira/downloads/atlassian-jira-software-7.12.1-x64.bin
    checksum: sha256:c01a978294137088f699cfde764ad89e9b48df3c0ce6b9c1503fe7eeb0be9310
  7.13.14:
    url: https://product-downloads.atlassian.com/software/jira/downloads/atlassian-jira-software-7.13.14-x64.bin
    checksum: sha256:c71754210be809903441735b8eea4f95f4ef9fa94003d9fbc404fecc2c4a01c8
  8.5.5:
    url: https://product-downloads.atlassian.com/software/jira/downloads/atlassian-jira-software-8.5.5-x64.bin
    checksum: sha256:07a95b111703c6a316a29b993387aff7dcf3d86de1251d06030ddce4eb10c62a
  8.13.0:
    url: https://product-downloads.atlassian.com/software/jira/downloads/atlassian-jira-software-8.13.0-x64.bin
    checksum: sha256:dc6d5ce0d9718adf1c3b0bbe5b0a744eeb46c072da2b775fdd5e7737f4b832b7

jira_versions_sequence: ['7.12.1','7.13.14','8.5.5','8.13.0']

# Atlassian Support recommended JVM arguments.
jira_jvm_support_recommended_args: >-
  -Datlassian.plugins.enable.wait=300
  -XX:+UnlockExperimentalVMOptions
  -XX:+UseCGroupMemoryLimitForHeap
  -XX:MaxRAMFraction=1

#-Djavax.net.ssl.trustStore=/path#
#-Djavax.net.ssl.trustStore
#-Dhttp.proxyHost#
#-Dhttp.proxyPort
#-Dhttps.proxyHost
#-Dhttps.proxyPort

# Session timeout.
#jira_session_timeout: "300"

jira_jmx:
  enable: no
#  remote_port: 3333
#  rmi_port: 3333
#  rmi_server_hostname: sh.1.1.1.11.nip.io
#  password: supersecret

jira_libraries: []
#  - url: https://github.com/javamelody/jira-confluence-javamelody/releases/download/1.83.0/jira-confluence-javamelody-1.83.0.jar
#    checksum: 2007bf47db63690f61a919cc828332d1d852c283c48137e07db608dd3c82e65e

# https://confluence.atlassian.com/x/PRCEOQ
jira_packages:
  RedHat: ['fontconfig']
  CentOS: ['dejavu-sans-fonts','fontconfig']