---
- name: Required packages
  package:
    name: "{{ haproxy_packages }}"

- name: Make dir
  file:
    path: "{{ haproxy_make_dir }}"
    state: directory

- name: Get source
  get_url:
    url: "{{ haproxy_versions[haproxy_version]['url'] }}"
    checksum: "{{ haproxy_versions[haproxy_version]['checksum'] }}"
    dest: "{{ haproxy_make_dir }}/{{ haproxy_versions[haproxy_version]['url']|basename }}"

- name: Extract source tar
  unarchive:
    src: "{{ haproxy_make_dir }}/{{ haproxy_versions[haproxy_version]['url']|basename }}"
    dest: "{{ haproxy_make_dir }}"
    remote_src: yes

- name: Make
  make:
    chdir: "{{ haproxy_make_dir }}/haproxy-{{ haproxy_version }}"
    params:
      TARGET: linux-glibc
      USE_OPENSSL: 1
      USE_ZLIB: 1
      USE_PCRE: 1
      USE_SYSTEMD: 1

- name: Make install
  make:
    chdir: "{{ haproxy_make_dir }}/haproxy-{{ haproxy_version }}"
    target: install
