---
- name: Systemd service
  template:
    src: sonar.unit.j2
    dest: /etc/systemd/system/sonarqube.service
    owner: root
    group: root
    mode: 0755
  when: "ansible_service_mgr == 'systemd'" 
  notify: 
    - systemctl-daemon-reload
    - restart sonarqube

- name: Ensure Sonar is running and set to start on boot.
  service: name=sonarqube state=started enabled=yes

- name: Allow Sonar time to build on first start.
  pause: seconds=180
  when: install_symlink.changed
  tags: ['skip_ansible_lint']

- name: Make sure Sonar is responding on the configured port.
  wait_for: port=9000 delay=3 timeout=300  