---
- name: systemd service
  template:
    src: jira.service.j2
    dest: /etc/systemd/system/jira.service
    owner: root
    group: root
    mode: 0755
  when: "ansible_service_mgr == 'systemd'" 
  notify: jira-systemctl-daemon-reload

- name: ensure service running and set to start on boot
  service: name=jira state=started enabled=yes
  when: jira_manual_upgrade == False