---
dependencies:
  - {role: lcm,                     tags: ansible }
  - {role: lvm,                     tags: lvm }
  - {role: ca,                      tags: ssl }
  - {role: ansible-agent,           tags: ansible }
  - {role: robertdebock.bootstrap,  tags: ansible }
  - {role: ansible-apt,             tags: apt, when: ansible_os_family == 'Debian' }
  - {role: ajsalminen.hosts,        tags: network }
#  - {role: ansible-hostname,        tags: hostname }
  - {role: Stouts.sudo,             tags: sudo }
  - {role: ANXS.openssh,            tags: openssh, when: ansible_os_family == 'Debian' }
  - {role: knopki.locale,           tags: locale }
#  - {role: manala.motd,             tags: motd }
  - {role: c2-alias,                tags: alias }
  - {role: marcelnijenhof.firewalld,tags: network, when: ansible_os_family == 'RedHat' }
  - {role: monit,                   tags: monitoring }
#  - {role: swid,                    tags: swid }
