---
# Confluence setup has been done if confluence.cfg.xml exists
# and if this file contains <setupStep>complete</setupStep>
# To determine if this is the case we use lineinfile module to
# check ( check_mode: yes ) if file would change if we put this
# text in ourselves. 

- name: "Check setup status"
  lineinfile:
    path: "{{ confluence_home_version_home }}/confluence.cfg.xml"
    regexp: "^.*?<setupStep>.*?</setupStep>$"
    line: "  <setupStep>complete</setupStep>"
    state: present
    create: yes
  check_mode: yes # don't actually replace
  register: complete_replace

- name: Confluence setup
  debug:
    msg: "Confluence has not been setup yet. Use a browser to navigate to http://localhost:{{ confluence_web_port }}  and complete Confluence setup"
  changed_when: true
  when: complete_replace is changed

- name: confluence.cfg.xml
  xml:
    path: "{{ confluence_home_version_home }}/confluence.cfg.xml"
    xpath: "/confluence-configuration/properties/property[@name='{{ item }}']"
    value: "{{ confluence_database_hibernate.generic[item] }}"
  when: not complete_replace is changed
  with_items: "{{ confluence_database_hibernate.generic }}"
  notify: confluence-systemctl-restart

- name: "confluence.cfg.xml {{ confluence_database_type }}"
  xml:
    path: "{{ confluence_home_version_home }}/confluence.cfg.xml"
    xpath: "/confluence-configuration/properties/property[@name='{{ item }}']"
    value: "{{ confluence_database_hibernate[confluence_database_type]['set'][item] }}"
  when: not complete_replace is changed
  with_items: "{{ confluence_database_hibernate[confluence_database_type]['set'] }}"
  notify: confluence-systemctl-restart

- name: "Remove from confluence.cfg.xml {{ confluence_database_type }}"
  xml:
    path: "{{ confluence_home_version_home }}/confluence.cfg.xml"
    xpath: "/confluence-configuration/properties/property[@name='{{ item }}']"
    state: absent
  when: not complete_replace is changed
  with_items: "{{ confluence_database_hibernate[confluence_database_type]['remove'] }}"
  notify: confluence-systemctl-restart

- name: Change temp dir location CONFSERVER-59613
  lineinfile:
    path: "{{ confluence_home_version_home }}/synchrony-args.properties"
    regexp: '^java.io.tmpdir='
    line: "java.io.tmpdir={{ confluence_home_version_home }}/temp"
  when: not complete_replace is changed
  notify: confluence-systemctl-restart
