---
- name: Restore file
  stat:
    path: "/tmp/RESTORE"
  register: restore_file

- name: Fail restore without confirmation
  fail:
    msg: To perform the restore confirm it with touch /tmp/RESTORE
  when: backup_restore_confirm == True and not restore_file.stat.exists

- name: Tmp restore folders
  file:
    path: "{{ backup_restore[item]['tmp'] }}"
    state: directory
    mode: 0700
  with_items: '{{ backup_restore }}'

- name: Tmp restore home folders
  file:
    path: "{{  backup_restore[item]['tmp'] }}/home"
    state: directory
    mode: 0700
  when: backup_restore[item]['home_tar'] is defined    
  with_items: '{{ backup_restore }}'

- name: Extract tar
  unarchive:
    src: "{{ backup_restore[item]['tar'] }}"
    remote_src: yes
    dest: "{{ backup_restore[item]['tmp'] }}"
  when: backup_restore[item]['tar'] is defined
  with_items: '{{ backup_restore }}'

- name: Stop service
  service:
    name: "{{ backup_restore[item]['stop_start_service'] }}"
    state: stopped
  when: 
    backup_restore[item]['stop_start_service'] is defined
  with_items: '{{ backup_restore }}'

- include_tasks: "restore_db_{{vars[item + '_database_type']|default('postgresql')}}.yml"
  when: 
    backup_restore_db == True
  with_items: '{{ backup_restore }}'

- include_tasks: "restore_files.yml"
  when: 
    backup_restore_home == True

- name: Mark restore performed
  lineinfile:
    dest: "{{ backup_restore[item]['restored-file'] }}"
    line: "{{ backup_restore[item]['backup-id'] }}"
  with_items: '{{ backup_restore }}'

- name: Delete restore file
  file:
    path: "/tmp/RESTORE"
    state: absent

- name: Delete tmp restore folders
  file:
    path: "{{ backup_restore[item]['tmp'] }}"
    state: absent
  with_items: '{{ backup_restore }}'

- name: Provision role after restore
  include_role:
    name: "{{ restore_role }}"
  with_items: '{{ backup_restore }}'
  loop_control:
    loop_var: restore_role
