---
postfix_config_file: /etc/postfix/main.cf

postfix_service_state: started
postfix_service_enabled: yes

postfix_inet_interfaces: all
postfix_inet_protocols: ipv4
postfix_mail_name: ESMTP

postfix_mynetworks: 
  - 127.0.0.0/8
  - 10.11.1.0/24
postfix_relayhost: "[mail.example.com]:587"
postfix_relay_domains: example.com
