---
- name: jira-application.properties
  template:
    dest: "{{ jira_home_version_app }}/atlassian-jira/WEB-INF/classes/jira-application.properties"
    owner: "{{ jira_owner }}"
    group: "{{ jira_group }}"
    src: jira-application.properties.j2
  notify: jira-systemctl-restart

- name: setenv.sh
  replace:
    path: "{{ jira_home_version_app }}/bin/setenv.sh"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - regexp: "JVM_MINIMUM_MEMORY=\".*?\"" 
      replace: "JVM_MINIMUM_MEMORY=\"{{ jira_jvm_minimum_memory }}\""
    - regexp: "JVM_MAXIMUM_MEMORY=\".*?\"" 
      replace: "JVM_MAXIMUM_MEMORY=\"{{ jira_jvm_maximum_memory }}\""
    - regexp: "JVM_SUPPORT_RECOMMENDED_ARGS=\".*?\"" 
      replace: "JVM_SUPPORT_RECOMMENDED_ARGS=\"{{ jira_jvm_support_recommended_args }}\""
    - regexp: ".?JIRA_HOME=\".*?\"" 
      replace: "JIRA_HOME=\"{{ jira_home_version_home }}\""
  no_log: true
  notify: jira-systemctl-restart

- name: server.xml
  template:
    dest: "{{ jira_home_version_app }}/conf/server.xml"
    owner: "{{ jira_owner }}"
    group: "{{ jira_group }}"
    src: server.xml.j2
  notify: jira-systemctl-restart

- name: Extra libaries
  get_url:
    checksum: "{{ item.checksum }}"
    dest: "{{ jira_home_version_app }}/atlassian-jira/WEB-INF/lib/{{ item.url|basename }}"
    owner: "{{ jira_owner }}"
    group: "{{ jira_group }}"
    url: "{{ item.url }}"
  with_items: "{{ jira_libraries }}" 
  notify: jira-systemctl-restart

- name: Oracle JDBC driver
  get_url:
    dest: "{{ jira_home_version_app }}/lib/{{ jira_database_ojdbc_jar_url|basename }}"
    group: "{{ jira_group }}"
    owner: "{{ jira_owner }}"
    url: "{{ jira_database_ojdbc_jar_url }}"
  when: jira_database_ojdbc_jar_url is defined
  notify:
    - jira-systemctl-restart
